### ISSUE TITLE
Question for `generate_spatial_weights_fixed_radius` when doing CCI analysis

### ISSUE THREAD

**Issue by jefferyUstc** [aristoteleo/spateo-release#184]
Hi, spateo-release team, nice work for stereo-seq data analysis. I've a question for the function `generate_spatial_weights_fixed_radius` where it estimates the radius when finding neighbors in a fixed radius manner. 

It calls the function `p_equiv_radius`:

```
def p_equiv_radius(p: float, sigma: float) -> float:
    """Find radius at which you eliminate fraction p of a radial Gaussian probability distribution with standard
    deviation sigma.
    """
    assert p < 1.0, f"p was {p}, must be less than 1"
    return np.sqrt(-2 * sigma**2 * np.log(p))
```

why the authors calculate the radius as ` np.sqrt(-2 * sigma**2 * np.log(p))`, rather than ` np.sqrt(-2 * sigma**2 * np.log(p*sigma*np.sqrt(2*np.pi)))`, which strictly followed the formula of Gaussian Distribution.

Further more, for the coordinates of ST data ,  how to estimate the sigma is better? any recommendations?

**Comment by dzhu8** [comment]
Sorry for the slight delay- thank you for trying out the package! I generally recommend using a fixed number of neighbors instead of a fixed distance because there isn't a great way to determine what the distance should be at this point. 

I'll provide part of the derivation and thought process here through code if curious:  we want to find the radius that corresponds to a given cumulative probability under this hypothetical Gaussian distribution that is drawn around each cell. We start with the formula for a Gaussian PDF, which the second equation there seems to derive from: 

f(x) = (1 / (sigma * sqrt(2*pi))) * exp(-(x - mu)**2 / (2*sigma**2))

The CDF provides a measure of the cumulative probability up to a given point- after a few operations this can be described by the integral:

(1 / sqrt(2π)) * ∫[-r/sigma, r/sigma] exp(-z^2 / 2) dz = p

The inverse cumulative distribution function (ICDF) can be used to solve this integral; we can backsolve for the value of z such that the ICDF = p: z = Φ^(-1)(p).

After substituting and several simplifying steps, we eventually rearrange the equation to solve for r: 

r = sigma * sqrt(-2 * log((1 / 2) * exp(Φ^(-1)(p)^2 / 2)))

There are more simplifying steps after this, with the key step being substitution of Φ^(-1)(p)^2 with -2 * log(p) (as an ICDF property), eventually leading to 
 
r = sigma * sqrt(-2 * log(p)), which can be rearranged to np.sqrt(-2 * sigma**2 * np.log(p)). 

Unfortunately, as I said above, there isn't a golden rule for defining this- most times when I do this, it involves checking the number of cells around each observation given the radius returned from a given sigma value and factoring in potential external information about which ligand-receptor mechanisms are likely at play. If these mostly involve membrane-bound ligands, the radius should capture only the nearest cells, for example. We generally prefer the formulations that find the number of neighboring cells, but Spateo is actively under development also welcomes community suggestions/contributions, so there may be better ways of doing this in the future!
