### ISSUE TITLE
如何在不能联网的集群使用需要预下载模型的函数进行细胞分割

### ISSUE THREAD

**Issue by yty420** [aristoteleo/spateo-release#200]
集群无法联网，但是函数自动要联网下载，无法指定本地上传的模型
st.cs.stardist(adata, equalize=2.0, out_layer='stardist_labels')
![image](https://github.com/aristoteleo/spateo-release/assets/100070204/f9f95a09-797e-4934-a356-90be3ba99f7f)

**Comment by Sichao25** [comment]
Hi, thanks for reporting the issue. The `st.cs.stardist()` uses `stardist` pre-trained model to perform segmentation. That's why it needs downloading. If you already have a model, you can use `stardist` directly like `labels, _ = model.predict_instances_big(img)` or `labels, _ = model.predict_instances(img)`.

**Comment by Danne1210** [comment]
> Hi, thanks for reporting the issue. The `st.cs.stardist()` uses `stardist` pre-trained model to perform segmentation. That's why it needs downloading. If you already have a model, you can use `stardist` directly like `labels, _ = model.predict_instances_big(img)` or `labels, _ = model.predict_instances(img)`.

I struggled the same problem, and I still can not figure out how to solve this problem. How to use the code, " `labels, _ = model.predict_instances_big(img)` or `labels, _ = model.predict_instances(img)`", and where should I put? Could you do me a help?
